spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://13.125.29.10:3000/hs_product?useSSL=false&characterEncoding=utf8
    username: hsdev
    password: wmp2018!@#
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

server:
  port: 8081